
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.1 EDK_MS1.53d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmpmc.h"

/*
* The configuration table for devices
*/

XMpmc_Config XMpmc_ConfigTable[] =
{
	{
		XPAR_MCB3_LPDDR_DEVICE_ID,
		XPAR_MCB3_LPDDR_MPMC_BASEADDR,
		XPAR_MCB3_LPDDR_MPMC_HIGHADDR,
		XPAR_MCB3_LPDDR_MPMC_CTRL_BASEADDR,
		XPAR_MCB3_LPDDR_INCLUDE_ECC_SUPPORT,
		XPAR_MCB3_LPDDR_USE_STATIC_PHY,
		XPAR_MCB3_LPDDR_PM_ENABLE,
		XPAR_MCB3_LPDDR_MEM_DATA_WIDTH,
		XPAR_MCB3_LPDDR_MEM_PART_NUM_BANK_BITS,
		XPAR_MCB3_LPDDR_MEM_PART_NUM_ROW_BITS,
		XPAR_MCB3_LPDDR_MEM_PART_NUM_COL_BITS,
		XPAR_MCB3_LPDDR_MEM_DQS_WIDTH,
		XPAR_MCB3_LPDDR_MPMC_CLK0_PERIOD_PS
	}
};


