#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\Xilinx\PRACTICAS_FPGA\AMPLIACION_GPIO\ficheros_p1\pr_1\system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /cygdrive/c/Xilinx/12.1/ISE_DS/EDK
NON_CYG_XILINX_EDK_DIR = C:/Xilinx/12.1/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = spartan6

DEVICE = xc6slx9csg324-2

LANGUAGE = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT) -msg __xps/ise/xmsgprops.lst \
                   $(MICROBLAZE_0_LIBG_OPT)

OBSERVE_PAR_OPTIONS = -error yes

KEYPAD_OUTPUT_DIR = KEYPAD
KEYPAD_OUTPUT = $(KEYPAD_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

MICROBLAZE_0_BOOTLOOP = $(BOOTLOOP_DIR)/microblaze_0.elf
MICROBLAZE_0_XMDSTUB = microblaze_0/code/xmdstub.elf

BRAMINIT_ELF_FILES =  $(KEYPAD_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe microblaze_0 $(KEYPAD_OUTPUT) 

ALL_USER_ELF_FILES = $(KEYPAD_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT) -msg __xps/ise/xmsgprops.lst -s mti -X C:/Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/


LIBRARIES =  \
       microblaze_0/lib/libxil.a 

LIBSCLEAN_TARGETS = microblaze_0_libsclean 

PROGRAMCLEAN_TARGETS = KEYPAD_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/microblaze_0_wrapper.ngc \
implementation/mb_plb_wrapper.ngc \
implementation/ilmb_wrapper.ngc \
implementation/dlmb_wrapper.ngc \
implementation/dlmb_cntlr_wrapper.ngc \
implementation/ilmb_cntlr_wrapper.ngc \
implementation/lmb_bram_wrapper.ngc \
implementation/usb_uart_wrapper.ngc \
implementation/leds_4bits_wrapper.ngc \
implementation/dip_switch_4bits_wrapper.ngc \
implementation/spi_flash_wrapper.ngc \
implementation/mcb3_lpddr_wrapper.ngc \
implementation/ethernet_mac_wrapper.ngc \
implementation/cdce913_i2c_wrapper.ngc \
implementation/clock_generator_0_wrapper.ngc \
implementation/mdm_0_wrapper.ngc \
implementation/proc_sys_reset_0_wrapper.ngc \
implementation/gpio_keypad_wrapper.ngc \
implementation/simon_periferico_0_wrapper.ngc \
implementation/gpio_display_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

# cygwin path for windows
SDK_EXPORT_DIR = SDK/SDK_Export/hw
CYG_SDK_EXPORT_DIR = /cygdrive/c//Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
CYG_SYSTEM_HW_HANDOFF = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
CYG_SYSTEM_HW_HANDOFF_BIT = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_BMM = $(SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
CYG_SYSTEM_HW_HANDOFF_BMM = $(CYG_SDK_EXPORT_DIR)/$(SYSTEM)_bd.bmm
SYSTEM_HW_HANDOFF_DEP = $(CYG_SYSTEM_HW_HANDOFF) $(CYG_SYSTEM_HW_HANDOFF_BIT) $(CYG_SYSTEM_HW_HANDOFF_BMM)

#################################################################
# SOFTWARE APPLICATION KEYPAD
#################################################################

KEYPAD_SOURCES = /cygdrive/c/Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/KEYPAD/KEYPAD.c 

KEYPAD_HEADERS = /cygdrive/c//Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/TestApp_Peripheral_microblaze_0/src/emaclite_header.h /cygdrive/c//Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/TestApp_Peripheral_microblaze_0/src/gpio_header.h /cygdrive/c//Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/TestApp_Peripheral_microblaze_0/src/iic_header.h /cygdrive/c//Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/TestApp_Peripheral_microblaze_0/src/spi_header.h /cygdrive/c//Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/TestApp_Peripheral_microblaze_0/src/uartlite_header.h /cygdrive/c//Xilinx/PRACTICAS_FPGA/AMPLIACION_GPIO/ficheros_p1/pr_1/TestApp_Peripheral_microblaze_0/src/xemaclite_example.h 

KEYPAD_CC = mb-gcc
KEYPAD_CC_SIZE = mb-size
KEYPAD_CC_OPT = -O2
KEYPAD_CFLAGS = 
KEYPAD_CC_SEARCH = # -B
KEYPAD_LIBPATH = -L./microblaze_0/lib/ # -L
KEYPAD_INCLUDES = -I./microblaze_0/include/  -ITestApp_Peripheral_microblaze_0/src/ # -I
KEYPAD_LFLAGS = # -l
KEYPAD_LINKER_SCRIPT = 
KEYPAD_LINKER_SCRIPT_FLAG = #-T $(KEYPAD_LINKER_SCRIPT) 
KEYPAD_CC_DEBUG_FLAG =  -g 
KEYPAD_CC_PROFILE_FLAG = # -pg
KEYPAD_CC_GLOBPTR_FLAG= # -mxl-gp-opt
KEYPAD_MODE = executable
KEYPAD_LIBG_OPT = -$(KEYPAD_MODE) microblaze_0
KEYPAD_CC_INFERRED_FLAGS= -mno-xl-soft-mul -mxl-pattern-compare -mcpu=v7.30.a 
KEYPAD_CC_START_ADDR_FLAG=  # -Wl,-defsym -Wl,_TEXT_START_ADDR=
KEYPAD_CC_STACK_SIZE_FLAG=  # -Wl,-defsym -Wl,_STACK_SIZE=
KEYPAD_CC_HEAP_SIZE_FLAG=  # -Wl,-defsym -Wl,_HEAP_SIZE=
KEYPAD_OTHER_CC_FLAGS= $(KEYPAD_CC_GLOBPTR_FLAG)  \
                  $(KEYPAD_CC_START_ADDR_FLAG) $(KEYPAD_CC_STACK_SIZE_FLAG) $(KEYPAD_CC_HEAP_SIZE_FLAG)  \
                  $(KEYPAD_CC_INFERRED_FLAGS)  \
                  $(KEYPAD_LINKER_SCRIPT_FLAG) $(KEYPAD_CC_DEBUG_FLAG) $(KEYPAD_CC_PROFILE_FLAG) 
