
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.1 EDK_MS1.53d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_DIP_SWITCH_4BITS_DEVICE_ID,
		XPAR_DIP_SWITCH_4BITS_BASEADDR,
		XPAR_DIP_SWITCH_4BITS_INTERRUPT_PRESENT,
		XPAR_DIP_SWITCH_4BITS_IS_DUAL
	},
	{
		XPAR_GPIO_DISPLAY_DEVICE_ID,
		XPAR_GPIO_DISPLAY_BASEADDR,
		XPAR_GPIO_DISPLAY_INTERRUPT_PRESENT,
		XPAR_GPIO_DISPLAY_IS_DUAL
	},
	{
		XPAR_GPIO_KEYPAD_DEVICE_ID,
		XPAR_GPIO_KEYPAD_BASEADDR,
		XPAR_GPIO_KEYPAD_INTERRUPT_PRESENT,
		XPAR_GPIO_KEYPAD_IS_DUAL
	},
	{
		XPAR_LEDS_4BITS_DEVICE_ID,
		XPAR_LEDS_4BITS_BASEADDR,
		XPAR_LEDS_4BITS_INTERRUPT_PRESENT,
		XPAR_LEDS_4BITS_IS_DUAL
	}
};


